name: 유닛 테스트
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["8"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - name: Node ${{ matrix.node }} 사용, OS ${{ matrix.os }} 사용
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: yarn 캐시 사용
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: npm 모듈 설치
        run: |
          yarn install
      - name: Mocha 테스트
        run: |
          yarn test:only
