name: Mocha Test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "10", "8"]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: |
          npm install
      - name: Generate coverage report
        run: |
          npm run test
