name: package 배포
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: node 설정
        uses: actions/setup-node@master
        with:
          node-version: 8
      - name: yarn 캐시 사용
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: npm 모듈 설치
        run: |
          yarn install
      - name: 빌드
        run: |
          yarn build
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCOUNT_TOKEN }}" > ~/.npmrc
      - name: 배포
        uses: primer/publish@emplums-patch-1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
          GPR_AUTH_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
          NPM_REGISTRY_URL: "npm.pkg.github.com"
