name: package 배포
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: node 설정
        uses: actions/setup-node@master
        with:
          node-version: 8
          registry-url: "https://registry.npmjs.org"
      - name: yarn 캐시 사용
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: npm 모듈 설치
        run: |
          yarn install
      - name: 빌드
        run: |
          yarn build
      - name: npm버전 추가
        run: |
          current_commit="$(git rev-parse --short HEAD)";
          npm version prerelease -preid "${current_commit}" -no-git-tag-version
      - name: npm에 배포
        run: npm publish --tag build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - name: gpr에 배포
        run: npm publish --tag build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
