name: Codecov Github Actions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 8.x
        uses: actions/setup-node@master
        with:
          node-version: 8.x
      - name: npm install
        run: |
          npm install
      - name: Generate coverage report
        run: |
          npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-nalae-lang
